### PR TITLE
execute onChange callback only if one is registered

### LINKED ISSUE #138: Useless Image reload triggered at keyup event
**What is the current behavior?**
If images were pasted or uploaded, so that you have `img` tags. Every single image is reloaded on every single keyup, which results in massive useless network traffic. 

**steps to reproduce**
set up everything as provided in docu
use any image as inital text, e.g.: `</img>` or just copy and paste something
focus editing area and start typing

 [example at codesandbox](https://codesandbox.io/s/goofy-varahamihira-03tfc)

**What is the expected behavior?**
Images should not be reloaded on every keyup or change

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue?**
Affected versions:
TinyMCE-Angular 3.4.0 / 3.3.0 / 3.2.0
Tested with Chrome Browser and TinyMCE 5.2.0

**Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
Seams to work with TinyMCE-Angular 3.1.0

### PR DESCRIPTION
**Pull request by tim-boerner**
This change is reducing the execution of the onChange callback only, if a callback is registered. This also avoids the cleaning mechanism of the editor [getContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) method.

It reduces the effect of #138 only to cases where a custom onChange callback is registered.

### CODE REVIEW

**Comment by tim-boerner** [comment]
Anything i can do, to get that merged?

**Comment by tim-boerner** [comment]
I realy would appreciate any response :-(

File: tinymce-angular-component/src/main/ts/editor/editor.component.ts [hunk 1]
```diff
@@ -173,18 +173,24 @@ constructor(
   private initEditor(editor: any) {
     editor.on('blur', () => this.ngZone.run(() => this.onTouchedCallback()));
     editor.on(this.modelEvents, () => {
-      this.ngZone.run(() => this.onChangeCallback(editor.getContent({ format: this.outputFormat })));
+      this.emitOnChange(editor);
```
Comment (jscasca) [inline tinymce-angular-component/src/main/ts/editor/editor.component.ts:176]: This probably should be inside the ngZone run

**Review by jscasca — COMMENTED** [review]
I'm happy to accept this as a temporary fix for the problem.

Just curious why run it outside the ngZone

**Review by jscasca — APPROVED** [review]

**Review by tiny-james — APPROVED** [review]
